/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cognito_identity_pool_id": "eu-north-1:2551c78f-42ba-44e1-bdf2-ed81971cff03",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_giKr3mPMB",
    "aws_user_pools_web_client_id": "5rj6ud7ornl6odgesokbgimbtb",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://6gvsdprubve25prdnd6jumwl7q.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-xxkq74shxfexjhdenp4cx25mem",
    "aws_user_files_s3_bucket": "forumapp20aec2d17f9d46feb9711bce42625345145748-dev",
    "aws_user_files_s3_bucket_region": "eu-north-1"
};


export default awsmobile;
